### ISSUE TITLE
After following instructions (I'm new though): 

### ISSUE THREAD

**Issue by bgrrtt** [stackstrap/craft-ops#1]
~/PWD ❯❯❯ fab setup

...

==> dev: Summary
==> dev: -------------
==> dev: Succeeded: 90 (changed=9)
==> dev: Failed:     0
==> dev: -------------
==> dev: Total states run:     90
==> web: VM not created. Moving on...
~/PWD ❯❯❯ vagrant up web                                                          
Bringing machine 'web' up with 'virtualbox' provider...
==> web: Box 'dummy' could not be found. Attempting to find and install...
    web: Box Provider: virtualbox
    web: Box Version: >= 0
==> web: Box file was not detected as metadata. Adding it directly...
==> web: Adding box 'dummy' (v0) for provider: virtualbox
    web: Downloading: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: virtualbox
Provider of box: aws

=============================================

Super thankful for any light you can shed!!

^^^ Looks like maybe I missed the ssh step...

**Comment by howardroark** [comment]
Hey @bgrrtt !  Sorry for being so late on this! I must have missed it.

So the idea behind this setup is that everything related to the `web` VM needs to happen within the `dev` vm.  This ensures that you can take advantage of an automatic configuration and not have to worry about variations between machines. 

I assume you were running this on your "host" machine.  Let me know if I am wrong in that assumption.

**Comment by howardroark** [comment]
Just to add to this... Don't hesitate to ask anything! I'm happy to help and it gives me a better sense of where people struggle :)

**Comment by howardroark** [comment]
Just closing this up as the `fab setup` command works a lot differently now and the web vm setup does not depend on Vagrant.  Vagrant is not really meant for production use, it was just an easy way to get rolling.  The setup now uses the boto library to create the web vm.
