### ISSUE TITLE
AWS import-key-pair error during 'fab setup'

### ISSUE THREAD

**Issue by joeygravlin** [stackstrap/craft-ops#2]
Hi Howard,

I've been playing around with your craft-ops repo and have run into an issue with the `fab setup` task. It generates both the admin and web key-pairs then fails with the following.

`Fatal error: local() encountered an error (return code 255) while executing 'aws ec2 import-key-pair --key-name` project_name `--public-key-material`...(contents of admin.pub)

From what I can tell, this should just work. Any suggestions?

Thanks in advance,

**Comment by howardroark** [comment]
Hey @joeygravlin !

So the `setup` function is pretty fragile as it stands.  It basically just runs `aws-cli` commands and stores their response.  The `aws-cli

**Comment by howardroark** [comment]
Closing this as the `fab setup` command now behaves much differently.  Should be more stable now... Hopefully!
